apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # clave-secreta-12345 = (base64) Y2xhdmUtc2VjcmV0YS0xMjM0NQ==
  # postgres = (base64) cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: Y2xhdmUtc2VjcmV0YS0xMjM0NQ==