# Versión de docker compose que se usará
version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      # ./, relativo al path donde está este docker compose
      # postgres, será un directorio que estará en la raíz de este docker-compose y donde los datos de la bd será enlazados
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com